version: '3.4'

x-common-env-vars: &common-env-vars
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql://postgres:mlecourse@34.64.195.37:5432
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql://postgres:mlecourse@34.64.195.37:5432
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__CORE__FERNET_KEY: "d6Vefz3G9U_ynXB3cr7y_Ak35tAHkEGAVxuz_B-jzWw="
  AIRFLOW__WEBSERVER__SECRET_KEY: "final_ddb8ce"
  AIRFLOW__WEBSERVER__RBAC: "True"
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
  ASTRONOMER_ENVIRONMENT: local

networks:
  airflow:
    driver: bridge

volumes:
  airflow_logs:
    driver: local

services:
  scheduler:
    image: final_ddb8ce/airflow:latest
    command: >
      bash -c "(airflow db upgrade || airflow upgradedb) && airflow scheduler"
    restart: unless-stopped
    networks:
      - airflow
    user: astro
    labels:
      io.astronomer.docker: "true"
      io.astronomer.docker.cli: "true"
      io.astronomer.docker.component: "airflow-scheduler"
    environment: *common-env-vars
    volumes:
      - /home/ubuntu/final_project/dags:/usr/local/airflow/dags:z
      - /home/ubuntu/final_project/plugins:/usr/local/airflow/plugins:z
      - /home/ubuntu/final_project/include:/usr/local/airflow/include:z
      - /home/ubuntu/final_project/tests:/usr/local/airflow/tests:z

      - /home/ubuntu/final_project/airflow_settings.yaml:/usr/local/airflow/airflow_settings.yaml:z

      
      - airflow_logs:/usr/local/airflow/logs
      
    

  webserver:
    image: final_ddb8ce/airflow:latest
    command: >
      bash -c 'if [[ -z "$$AIRFLOW__API__AUTH_BACKEND" ]] && [[ $$(pip show -f apache-airflow | grep basic_auth.py) ]];
        then export AIRFLOW__API__AUTH_BACKEND=airflow.api.auth.backend.basic_auth ;
        else export AIRFLOW__API__AUTH_BACKEND=airflow.api.auth.backend.default ; fi &&
        { airflow users create "$$@" || airflow create_user "$$@" ; } &&
        { airflow sync-perm || airflow sync_perm ;} &&
        airflow webserver' -- -r Admin -u admin -e admin@example.com -f admin -l user -p admin
    restart: unless-stopped
    networks:
      - airflow
    user: astro
    labels:
      io.astronomer.docker: "true"
      io.astronomer.docker.cli: "true"
      io.astronomer.docker.component: "airflow-webserver"
    depends_on:
      - scheduler
    environment: *common-env-vars
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - /home/ubuntu/final_project/dags:/usr/local/airflow/dags:z
      - /home/ubuntu/final_project/plugins:/usr/local/airflow/plugins:z
      - /home/ubuntu/final_project/include:/usr/local/airflow/include:z
      - /home/ubuntu/final_project/tests:/usr/local/airflow/tests:z
      
      - airflow_logs:/usr/local/airflow/logs
      
    healthcheck:
      test: curl --fail http://webserver:8080/health || exit 1
      interval: 2s
      retries: 15
      start_period: 5s
      timeout: 60s
    

  triggerer:
    image: final_ddb8ce/airflow:latest
    command: >
      bash -c "(airflow db upgrade || airflow upgradedb) && airflow triggerer"
    restart: unless-stopped
    networks:
      - airflow
    user: astro
    labels:
      io.astronomer.docker: "true"
      io.astronomer.docker.cli: "true"
      io.astronomer.docker.component: "airflow-triggerer"
    environment: *common-env-vars
    volumes:
      - /home/ubuntu/final_project/dags:/usr/local/airflow/dags:z
      - /home/ubuntu/final_project/plugins:/usr/local/airflow/plugins:z
      - /home/ubuntu/final_project/include:/usr/local/airflow/include:z
      
      - airflow_logs:/usr/local/airflow/logs
      
    

